In [1]:
"""
We go through the most basic and essential tensor operations
that really build the foundation to TensorFlow 2.0 and is
important to know before moving on to building neural networks
"""

import tensorflow as tf

## Tensor Initialization

In [2]:
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [3]:
# Matrix of three colums and two rows (2 by 3 matrix)
x = tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [4]:
# 3 by 3 matrix with values of 1
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [5]:
# 2 by 3 matrix with values of zeros
x = tf.zeros((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [6]:
"""
In linear algebra, the identity or identity matrix
is the matrix that has ONE in all elements of the
main diagonal and ZERO in all other elements.
"""

# 4 by 4 matrix with values of 1
x = tf.eye(4) # I (eye) for the identity matrix
print(x)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [7]:
# ???
x = tf.random.normal((3,3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[-0.4080014   0.07598507  2.1619554 ]
 [ 0.55590314 -1.6559517   0.36959133]
 [-1.3597547  -0.22469907 -0.69876945]], shape=(3, 3), dtype=float32)


In [8]:
# Values between zero and one in a 2 by 3 matrix

x = tf.random.uniform((2,3), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.77365017 0.47819734 0.08265984]
 [0.84914124 0.12654293 0.63116264]], shape=(2, 3), dtype=float32)


In [9]:
# Vector of values starting from one and ends at nine
# delta set the step
x = tf.range(start=1, limit=10, delta=2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [10]:
# Convert x to a specific type
# tf.float(16, 32, 64), tf.int(8, 16, 32, 64), tf.bool

x = tf.cast(x, dtype=tf.float64)
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


## Tensor Mathematical Operations

In [11]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

In [12]:
# Adding vectors (1+9 | 2+8 | 3+7)
z = tf.add(x, y)
print(z)

# OR

print(x + y)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [13]:
# Subtract vectors (1-9 | 2-8 | 3-7)
z = tf.subtract(x, y)
print(z)

# OR

print(x - y)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [14]:
# Divide vectors (1/9 | 2/8 | 3/7)
z = tf.divide(x, y)
print(z)

# OR

print(x/y)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [15]:
# Multiply vectors (1*9 | 2*8 | 3*7)
z = tf.multiply(x, y)
print(z)

# OR

print(x*y)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [16]:
"""In mathematics, the dot product
is an algebraic operationthat takes
two sequences of numbers of equal
length and adds their product

x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

z = (1*9) + (2*8) + (3*7)
"""

z = tf.tensordot(x, y, axes=1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [17]:
# Multiply every element with a number

z = x**5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [18]:
"""
For matrix multiplication, the
number of columns in the first matrix
must be equal to the number of rows in
the second matrix.
The result matrix has the number of rows
of the first and the number of columns of
the second matrix.
"""

# Matrix Multipication

x = tf.random.normal((3,5))
y = tf.random.normal((5,4))

z = tf.matmul(x, y)
print(z)
# OR

z = x @ y
print(z)

tf.Tensor(
[[ 2.8913946 -4.576058   1.1182126 -3.3144627]
 [-2.0845659  4.0514665 -0.215361   3.341424 ]
 [-1.1160663  3.847392   1.8725822  2.3342535]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[ 2.8913946 -4.576058   1.1182126 -3.3144627]
 [-2.0845659  4.0514665 -0.215361   3.341424 ]
 [-1.1160663  3.847392   1.8725822  2.3342535]], shape=(3, 4), dtype=float32)


## Tensor Indexing

In [19]:
x = tf.constant([0,1,1,2,3,1,2,3])

In [20]:
# Print all elements
print(x[:])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)


In [21]:
# Exlude first element from printing
print(x[1:])

tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)


In [22]:
# Print only second and third element
print(x[1:3])

tf.Tensor([1 1], shape=(2,), dtype=int32)


In [23]:
# Print element by step 2
print(x[::2])

tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)


In [24]:
# Print element in a revarse order
print(x[::-1])

tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [25]:
# We can gather the specific indices from a vector.

# We create a vector with the numbers of indexes we want to collect.
indices = tf.constant([0,3])

# We use .gather to collect from x the values from the indexes.
x_ind = tf.gather(x, indices)
print(x_ind)

tf.Tensor([0 2], shape=(2,), dtype=int32)


## Tensor Reshaping

In [26]:
# Vector of nine elements
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [27]:
# Reshape in a 3 by 3 matrix
x = tf.reshape(x,(3,3))
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [28]:
# Change columns to rows

x = tf.transpose(x, perm=[1,0]) # perm=[1,0] swap the axis
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
